CREATE TABLE IF NOT EXISTS `#__cjlib_config`
(
    `config_name`  varchar(255) NOT NULL,
    `config_value` text         NOT NULL,
    PRIMARY KEY (`config_name`)
) CHARACTER SET `utf8`;

CREATE TABLE IF NOT EXISTS `#__corejoomla_messagequeue`
(
    `id`         int(10) unsigned    NOT NULL AUTO_INCREMENT,
    `status`     tinyint(4) unsigned NOT NULL DEFAULT '0',
    `to_addr`    varchar(128)        NOT NULL,
    `cc_addr`    varchar(128)                 DEFAULT NULL,
    `bcc_addr`   varchar(128)                 DEFAULT NULL,
    `html`       tinyint(1)          NOT NULL DEFAULT '1',
    `message_id` int(10) unsigned    NOT NULL,
    `params`     mediumtext,
    `created`    datetime            NULL     DEFAULT NULL,
    `processed`  datetime            NULL     DEFAULT NULL,
    `retries`    INT(10) unsigned    NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`) USING BTREE,
    INDEX `idx_corejoomla_messagequeue_status` (`status`) USING BTREE,
    INDEX `idx_corejoomla_messagequeue_created` (`created`) USING BTREE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  DEFAULT COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__corejoomla_messages`
(
    `id`          int(10) unsigned NOT NULL AUTO_INCREMENT,
    `asset_id`    int(10) unsigned NOT NULL,
    `asset_name`  varchar(64)      NOT NULL,
    `subject`     varchar(255)     NOT NULL,
    `description` mediumtext       NOT NULL,
    `params`      varchar(999)          DEFAULT NULL,
    `created`     datetime         NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  DEFAULT COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__corejoomla_rating`
(
    `item_id`       int(10) unsigned NOT NULL,
    `asset_id`      int(10) unsigned NOT NULL,
    `total_ratings` int(10) unsigned NOT NULL DEFAULT '0',
    `sum_rating`    int(10) unsigned NOT NULL DEFAULT '0',
    `rating`        decimal(4, 2)    NOT NULL DEFAULT '0.00',
    PRIMARY KEY (`item_id`, `asset_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  DEFAULT COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__corejoomla_rating_details`
(
    `id`         INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `asset_id`   INTEGER UNSIGNED NOT NULL,
    `item_id`    INTEGER UNSIGNED NOT NULL,
    `action_id`  INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `rating`     INTEGER UNSIGNED NOT NULL,
    `created_by` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `created`    DATETIME         NULL     DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  DEFAULT COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__corejoomla_assets`
(
    `id`       INTEGER UNSIGNED NOT NULL,
    `name`     VARCHAR(64)      NOT NULL,
    `version`  VARCHAR(32)      NOT NULL,
    `released` DATE             NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  DEFAULT COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__corejoomla_countries`
(
    `id`           INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `country_code` VARCHAR(3)       NOT NULL,
    `country_name` VARCHAR(64)      NOT NULL,
    `language`     VARCHAR(6)       NOT NULL DEFAULT '*',
    `published`    TINYINT(3)       NOT NULL DEFAULT '1',
    `publish_up`   DATETIME         NULL     DEFAULT NULL,
    `publish_down` DATETIME         NULL     DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `idx_corejoomla_countries_uniq` (`country_code`, `language`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  DEFAULT COLLATE = utf8mb4_unicode_ci;

INSERT INTO `#__corejoomla_countries`(country_name, country_code)
VALUES ('Afghanistan', 'AF'),
       ('Åland Islands', 'AX'),
       ('Albania', 'AL'),
       ('Algeria', 'DZ'),
       ('American Samoa', 'AS'),
       ('Andorra', 'AD'),
       ('Angola', 'AO'),
       ('Anguilla', 'AI'),
       ('Antarctica', 'AQ'),
       ('Antigua And Barbuda', 'AG'),
       ('Argentina', 'AR'),
       ('Armenia', 'AM'),
       ('Aruba', 'AW'),
       ('Australia', 'AU'),
       ('Austria', 'AT'),
       ('Azerbaijan', 'AZ'),
       ('Bahamas', 'BS'),
       ('Bahrain', 'BH'),
       ('Bangladesh', 'BD'),
       ('Barbados', 'BB'),
       ('Belarus', 'BY'),
       ('Belgium', 'BE'),
       ('Belize', 'BZ'),
       ('Benin', 'BJ'),
       ('Bermuda', 'BM'),
       ('Bhutan', 'BT'),
       ('Bolivia', 'BO'),
       ('Bosnia And Herzegovina', 'BA'),
       ('Botswana', 'BW'),
       ('Bouvet Island', 'BV'),
       ('Brazil', 'BR'),
       ('British Indian Ocean Territory', 'IO'),
       ('Brunei Darussalam', 'BN'),
       ('Bulgaria', 'BG'),
       ('Burkina Faso', 'BF'),
       ('Burundi', 'BI'),
       ('Cambodia', 'KH'),
       ('Cameroon', 'CM'),
       ('Canada', 'CA'),
       ('Cape Verde', 'CV'),
       ('Cayman Islands', 'KY'),
       ('Central African Republic', 'CF'),
       ('Chad', 'TD'),
       ('Chile', 'CL'),
       ('China', 'CN'),
       ('Christmas Island', 'CX'),
       ('Cocos Keeling Islands', 'CC'),
       ('Colombia', 'CO'),
       ('Comoros', 'KM'),
       ('Congo', 'CG'),
       ('Congo', 'CD'),
       ('Cook Islands', 'CK'),
       ('Costa Rica', 'CR'),
       ('Côte D\'ivoire', 'CI'),
       ('Croatia', 'HR'),
       ('Cuba', 'CU'),
       ('Cyprus', 'CY'),
       ('Czech Republic', 'CZ'),
       ('Denmark', 'DK'),
       ('Djibouti', 'DJ'),
       ('Dominica', 'DM'),
       ('Dominican Republic', 'DO'),
       ('Ecuador', 'EC'),
       ('Egypt', 'EG'),
       ('El Salvador', 'SV'),
       ('Equatorial Guinea', 'GQ'),
       ('Eritrea', 'ER'),
       ('Estonia', 'EE'),
       ('Ethiopia', 'ET'),
       ('Falkland Islands Malvinas', 'FK'),
       ('Faroe Islands', 'FO'),
       ('Fiji', 'FJ'),
       ('Finland', 'FI'),
       ('France', 'FR'),
       ('French Guiana', 'GF'),
       ('French Polynesia', 'PF'),
       ('French Southern Territories', 'TF'),
       ('Gabon', 'GA'),
       ('Gambia', 'GM'),
       ('Georgia', 'GE'),
       ('Germany', 'DE'),
       ('Ghana', 'GH'),
       ('Gibraltar', 'GI'),
       ('Greece', 'GR'),
       ('Greenland', 'GL'),
       ('Grenada', 'GD'),
       ('Guadeloupe', 'GP'),
       ('Guam', 'GU'),
       ('Guatemala', 'GT'),
       ('Guernsey', 'GG'),
       ('Guinea', 'GN'),
       ('Guinea-Bissau', 'GW'),
       ('Guyana', 'GY'),
       ('Haiti', 'HT'),
       ('Heard Island And Mcdonald Islands', 'HM'),
       ('Honduras', 'HN'),
       ('Hong Kong', 'HK'),
       ('Hungary', 'HU'),
       ('Iceland', 'IS'),
       ('India', 'IN'),
       ('Indonesia', 'ID'),
       ('Iran', 'IR'),
       ('Iraq', 'IQ'),
       ('Ireland', 'IE'),
       ('Isle Of Man', 'IM'),
       ('Israel', 'IL'),
       ('Italy', 'IT'),
       ('Jamaica', 'JM'),
       ('Japan', 'JP'),
       ('Jersey', 'JE'),
       ('Jordan', 'JO'),
       ('Kazakhstan', 'KZ'),
       ('Kenya', 'KE'),
       ('Kiribati', 'KI'),
       ('Korea', 'KP'),
       ('Korea', 'KR'),
       ('Kuwait', 'KW'),
       ('Kyrgyzstan', 'KG'),
       ('Lao People\'s Democratic Republic', 'LA'),
       ('Latvia', 'LV'),
       ('Lebanon', 'LB'),
       ('Lesotho', 'LS'),
       ('Liberia', 'LR'),
       ('Libyan Arab Jamahiriya', 'LY'),
       ('Liechtenstein', 'LI'),
       ('Lithuania', 'LT'),
       ('Luxembourg', 'LU'),
       ('Macao', 'MO'),
       ('Macedonia', 'MK'),
       ('Madagascar', 'MG'),
       ('Malawi', 'MW'),
       ('Malaysia', 'MY'),
       ('Maldives', 'MV'),
       ('Mali', 'ML'),
       ('Malta', 'MT'),
       ('Marshall Islands', 'MH'),
       ('Martinique', 'MQ'),
       ('Mauritania', 'MR'),
       ('Mauritius', 'MU'),
       ('Mayotte', 'YT'),
       ('Mexico', 'MX'),
       ('Micronesia', 'FM'),
       ('Moldova', 'MD'),
       ('Monaco', 'MC'),
       ('Mongolia', 'MN'),
       ('Montenegro', 'ME'),
       ('Montserrat', 'MS'),
       ('Morocco', 'MA'),
       ('Mozambique', 'MZ'),
       ('Myanmar', 'MM'),
       ('Namibia', 'NA'),
       ('Nauru', 'NR'),
       ('Nepal', 'NP'),
       ('Netherlands', 'NL'),
       ('Netherlands Antilles', 'AN'),
       ('New Caledonia', 'NC'),
       ('New Zealand', 'NZ'),
       ('Nicaragua', 'NI'),
       ('Niger', 'NE'),
       ('Nigeria', 'NG'),
       ('Niue', 'NU'),
       ('Norfolk Island', 'NF'),
       ('Northern Mariana Islands', 'MP'),
       ('Norway', 'NO'),
       ('Oman', 'OM'),
       ('Pakistan', 'PK'),
       ('Palau', 'PW'),
       ('Palestinian Territory', 'PS'),
       ('Panama', 'PA'),
       ('Papua New Guinea', 'PG'),
       ('Paraguay', 'PY'),
       ('Peru', 'PE'),
       ('Philippines', 'PH'),
       ('Pitcairn', 'PN'),
       ('Poland', 'PL'),
       ('Portugal', 'PT'),
       ('Puerto Rico', 'PR'),
       ('Qatar', 'QA'),
       ('Réunion', 'RE'),
       ('Romania', 'RO'),
       ('Russian Federation', 'RU'),
       ('Rwanda', 'RW'),
       ('Saint Barth�lemy', 'BL'),
       ('Saint Helena', 'SH'),
       ('Saint Kitts And Nevis', 'KN'),
       ('Saint Lucia', 'LC'),
       ('Saint Martin', 'MF'),
       ('Saint Pierre And Miquelon', 'PM'),
       ('Saint Vincent And The Grenadines', 'VC'),
       ('Samoa', 'WS'),
       ('San Marino', 'SM'),
       ('Sao Tome And Principe', 'ST'),
       ('Saudi Arabia', 'SA'),
       ('Senegal', 'SN'),
       ('Serbia', 'RS'),
       ('Seychelles', 'SC'),
       ('Sierra Leone', 'SL'),
       ('Singapore', 'SG'),
       ('Slovakia', 'SK'),
       ('Slovenia', 'SI'),
       ('Solomon Islands', 'SB'),
       ('Somalia', 'SO'),
       ('South Africa', 'ZA'),
       ('South Georgia And The South Sandwich Islands', 'GS'),
       ('Spain', 'ES'),
       ('Sri Lanka', 'LK'),
       ('Sudan', 'SD'),
       ('Suriname', 'SR'),
       ('Svalbard And Jan Mayen', 'SJ'),
       ('Swaziland', 'SZ'),
       ('Sweden', 'SE'),
       ('Switzerland', 'CH'),
       ('Syrian Arab Republic', 'SY'),
       ('Taiwan', 'TW'),
       ('Tajikistan', 'TJ'),
       ('Tanzania', 'TZ'),
       ('Thailand', 'TH'),
       ('Timor-Leste', 'TL'),
       ('Togo', 'TG'),
       ('Tokelau', 'TK'),
       ('Tonga', 'TO'),
       ('Trinidad And Tobago', 'TT'),
       ('Tunisia', 'TN'),
       ('Turkey', 'TR'),
       ('Turkmenistan', 'TM'),
       ('Turks And Caicos Islands', 'TC'),
       ('Tuvalu', 'TV'),
       ('Uganda', 'UG'),
       ('Ukraine', 'UA'),
       ('United Arab Emirates', 'AE'),
       ('United Kingdom', 'GB'),
       ('United States', 'US'),
       ('United States Minor Outlying Islands', 'UM'),
       ('Uruguay', 'UY'),
       ('Uzbekistan', 'UZ'),
       ('Vanuatu', 'VU'),
       ('Vatican City State', 'VA'),
       ('Venezuela', 'VE'),
       ('Viet Nam', 'VN'),
       ('Virgin Islands British', 'VG'),
       ('Virgin Islands U.S.', 'VI'),
       ('Wallis And Futuna', 'WF'),
       ('Western Sahara', 'EH'),
       ('Yemen', 'YE'),
       ('Zambia', 'ZM'),
       ('Zimbabwe', 'ZW'),
       ('European Union', 'EU'),
       ('United Kingdom', 'UK'),
       ('Ascension Island', 'AC'),
       ('Clipperton Island', 'CP'),
       ('Diego Garcia', 'DG'),
       ('Ceuta, Melilla', 'EA'),
       ('France, Metropolitan', 'FX'),
       ('Canary Islands', 'IC'),
       ('USSR', 'SU'),
       ('Tristan da Cunha', 'TA'),
       ('Unknown', 'XX')
ON DUPLICATE KEY UPDATE country_code=
                            values(country_code);